export const SET_PROPERTIES = "SET_PROPERTIES";
export const SET_PROPERTIES_TEN_DAYS = "SET_PROPERTIES_TEN_DAYS";
export const SET_PROPERTIES_FINISHED = "SET_PROPERTIES_FINISHED";
export const SET_PROPERTIES_EMPTY = "SET_PROPERTIES_EMPTY";
export const SET_UNITS = "SET_UNITS";
export const SET_CURRENT_PROPERTIES = "SET_CURRENT_PROPERTIES";
export const SET_CURRENT_UNITS = "SET_CURRENT_UNITS";
